version: "3.3"

services:
  # we use redis pub/sub to share events between the services
  redis:
    image: redis:5-alpine

  graphql:
    image: node:10-alpine
    working_dir: /node
    command: yarn start
    volumes:
      - ./graphql:/node
    ports:
      - 80:80
    depends_on:
      - redis

  dice:
    image: node:10-alpine
    working_dir: /node
    command: yarn start
    volumes:
      - ./dice:/node
    depends_on:
      - redis
      - dice-postgres

  dice-postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_PASSWORD=password

  statistic:
    image: node:10-alpine
    working_dir: /node
    command: yarn start
    volumes:
      - ./statistic:/node
    depends_on:
      - redis
      - statistic-postgres

  statistic-postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_PASSWORD=password
